[package]
name = "struxio-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "struxio-api"
path = "src/main.rs"

[lib]
name = "struxio_api"
path = "src/lib.rs"

[dependencies]
struxio-common = { workspace = true }
struxio-db = { workspace = true }
sqlx = { workspace = true }
struxio-core = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-credential-types = { workspace = true }
